import type { Metadata } from "next";
import Footer from "@/components/sections/footer";
import { Navbar } from "@/components/structure/navbar";
import { Container } from "@/components/ui/container";
import { siteUrl } from "@/lib/site";
import { PlatformModal } from "@/components/ui/platform-modal";

const TITLE = "Terms & Conditions — Cyberwall";
const DESCRIPTION =
  "The terms that apply when you use Cyberwall to verify suspicious messages, links, calls, or files.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: {
    canonical: `${siteUrl}/terms`,
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${siteUrl}/terms`,
    type: "website",
  },
  twitter: {
    card: "summary",
    title: TITLE,
    description: DESCRIPTION,
  },
};

const SECTIONS = [
  {
    category: "Service",
    body: (
      <p>
        Cyberwall is a free public safety tool operated by Kerala Police that
        provides automated risk assessments of suspicious messages, links,
        calls, files, and financial details submitted by users, via WhatsApp,
        Telegram, PolApp, or this website.
      </p>
    ),
  },
  {
    category: "Advisory nature",
    body: (
      <p>
        Results, including trust scores and recommendations, are advisory only,
        generated by automated analysis. They are not a legal determination and
        do not guarantee that a website, message, number, or file is genuinely
        safe or unsafe. You remain responsible for your own decisions.
      </p>
    ),
  },
  {
    category: "No liability",
    body: (
      <p>
        Kerala Police is not liable for any financial loss, damage, or harm
        arising from reliance on Cyberwall&apos;s output. Always exercise
        independent judgment, especially before making payments or sharing
        personal information.
      </p>
    ),
  },
  {
    category: "Acceptable use",
    body: (
      <ul className="list-disc space-y-1.5 pl-5">
        <li>
          Don&apos;t submit content you don&apos;t have the right to share
        </li>
        <li>
          Don&apos;t use the service to harass, impersonate, or defraud others
        </li>
        <li>
          Don&apos;t attempt to disrupt, reverse-engineer, or abuse the service
        </li>
        <li>
          Don&apos;t submit malware or illegal content other than for legitimate
          safety checks
        </li>
      </ul>
    ),
  },
  {
    category: "Intellectual property",
    body: (
      <p>
        The Cyberwall name, branding, and content on this site belong to Kerala
        Police unless otherwise stated.
      </p>
    ),
  },
  {
    category: "Changes",
    body: (
      <p>
        These terms may be updated periodically. Continued use of Cyberwall
        after changes are posted constitutes acceptance of the revised terms.
      </p>
    ),
  },
  {
    category: "Governing law",
    body: (
      <p>
        These terms are governed by the laws of India, with courts in Kerala
        having jurisdiction.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-16 pb-24 md:pt-20">
        <Container>
          <h1 className="font-nunito mt-6 text-4xl font-bold tracking-tight text-neutral-950 md:text-5xl">
            Terms & Conditions
          </h1>
          <p className="mt-4 max-w-xl text-base leading-relaxed text-neutral-600 md:text-lg">
            Last updated: 7 August 2026
          </p>
          <div className="mt-12 space-y-12">
            {SECTIONS.map((section) => (
              <section key={section.category}>
                <div className="mt-2">
                  <div className="rounded-3xl bg-white px-6 py-6 text-base leading-relaxed text-neutral-700 md:px-8 space-y-3">
                    <h2 className="font-nunito text-lg font-bold text-brand ">
                      {section.category}
                    </h2>
                    {section.body}
                  </div>
                </div>
              </section>
            ))}
          </div>
        </Container>
      </main>
      <Footer />
      <PlatformModal />
    </>
  );
}
